language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjcasey
  password:
    secure: HNyMAtyMUzgB20CzxwsNvXtFGzdUD3xvzCjtN9aaD0cHZpA+NBeCX+dnBjpLg7CnYmi6Vgpjjes3GCGrCKe5jnza/WBrEQvjuTUGokFnUMs+glRqGogamBfc/ZN2MBPP6i/eC9H7RD4KoFhDxNkYBvorUJ1I82D3Wp7UmUIToRTu+eUF3Ag6W6Ag1Vnxlf8fZ2mbEp7lhREixl6smOjlQJdKY+1niXeIalfNn5EeaxW0JAipQ/E2XoO8XeOD3wmU5pfpxeP3nYpgWvTKWpVa7WeWIA0VgMLFPL/heK/DtrciDeWspOyl+//gkoLFpdSgbcqPLaSsaqtYQ5CUokhIm2/nRMgACYuIp2VHe4R0hBcOqFZoYeDmn/j0ty9QYZzVqoZiJBDKM6ZozglvzTxxnRIOlveNUfcNTfSXdru+yPAVbEd5dxJq/PJJdQkPFKjDfHtNSvb54GcT5ZpHC/Q/P3MiwP+nx+QsB9ZbmPwNYapIw7/hMRsHfsf4xbMrDju8ldZdy1aiuMpCYI6dZNdT4G0U75xdqK6R7uaPz3n4o2txR4AZePwdd/PE0+Pw3Odb3S1X3UmmkxzfjcablP1zINwqjGv11RJATbO9lYdP3+vHyTk+eOQIA8dMq/HMwHlKxW22yMYVsAmT74urURgofbbf5pf6ZQOZlHEbrb3MGBo=
  on:
    tags: true
    repo: sjcasey21/arma-lisp
    python: 3.7
